version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 7512:7512
    depends_on:
      - kuzzle
    volumes:
      - ./docker-compose/nginx/kuzzle.conf:/etc/nginx/conf.d/kuzzle.conf

  kuzzle:
    image: kuzzleio/cluster
    volumes:
     - ./docker-compose/config/kuzzlerc.prod:/etc/kuzzlerc
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DEBUG: ${DEBUG:-none}
      DEBUG_COLORS: ${DEBUG_COLORS:-on}

  redis:
    image: redis:3.2

  elasticsearch:
    image: kuzzleio/elasticsearch:5.6.10
    ulimits:
      nofile: 65536
    environment:
      cluster.name: kuzzle

